### ISSUE TITLE
Selector morph instead of page morph

### ISSUE THREAD

**Issue by arambert** [joshleblanc/view_component_reflex#100]
Hi,
First let me thank you for this awesome gem!

I'd like to use VCR for simple UI components like autocomplete. For autocomplete for instance we run the reflex at each key pressed and we need a lot of reactivity.

Overall it works well but it seems that the full page is reloaded / re-rendered at each key pressed and therefore we are loosing a lot of time when we could only render the component, especially when the page is a big one.

If I understand it correctly, that would be because VCR is running page morphs. 
Would it be possible to use selector morphs with VCR and avoid rendering the whole page?

Thanks a lot!

**Comment by omarluq** [comment]
the `refresh!` function calls a selector morph, example:
```ruby
def my_reflex
  refresh! '#my-special-element'
end
# the above reflex will trigger the following under the hood
cable_ready.morph(
   selector: '#my-special-element',
   html: html.inner_html,
   children_only: true,
   permanent_attribute_name: "data-reflex-permanent",
   reflex_id: reflex_id)
```
if you have a more customized case you can call `prevent_refresh!` followed by a cable_ready call, ex:
```ruby
def my_reflex
  prevent_refresh!
  cable_ready.morph(
   selector: '#my-special-element',
   html: html.inner_html,
   children_only: true,
   permanent_attribute_name: "data-reflex-permanent",
   reflex_id: reflex_id)
end
```

**Comment by omarluq** [comment]
Im not quite sure but I think it has to do with persisting the value of omitted instances variables across renders, perhaps @joshleblanc can speak to that a little.
I will say that I tend to avoid omitting instance variables from the state in most of my projects unless I absolutely have to.

**Comment by arambert** [comment]
Thank you for your answer.
Another question: is it possible to "manually" render a component (and use the result in a morph) in a reflex action in a VCR component?
I've tried render & render_in (with & without view_context) and I could not make it work, I could not find how to get the controller or the view_context (always nil in my attempts). 
For instance, let's take a reflex named "on_save" : 
```ruby 
def on_save
   html = # what to put here, for instance to render NotificationComponent.new(message: "Congrats!")
   prevent_refresh!
   cable_ready.morph(
     selector: '#my-special-element',
     html: html)
end
```

**Comment by omarluq** [comment]
if it's a vanilla VC you can by calling `ApplicationController.render` explicitly, e.g:
```ruby
def on_save
   prevent_refresh!
   html = NotificationComponent.new(message: "Congrats!")
   cable_ready.morph(
     selector: '#my-special-element',
     html: ApplicationController.render(html, layout: false))
end
``` 

you can take a look at https://github.com/omarluq/ol_portfolio/tree/main/app/components for some more examples

**Comment by joshleblanc** [comment]
Re: "Why is it doing a page morph"

When you omit variables from state, we can't recreate the component at will anymore. What's happening is what we receive a websocket request for a reflex, we create an empty instantiation of the component (skipping the initialize call), then manually populate the instance variables from state - this allows us to run the reflex function against any local instance variables. 

However, when it comes time to render, it will fail if any of those instance variables are omitted (for example, a form) because it'll be running against a nil reference.

To get around that, we do a page morph, which forces the component to get fully initialized, at which point we replace any of the stale values with the new ones from state.

Hopefully that makes sense
