### ISSUE TITLE
Component Key should not only depend on calling file & line number

### ISSUE THREAD

**Issue by arambert** [joshleblanc/view_component_reflex#101]
IMHO we should be able to use a VCR inside an `each` loop in a view. For instance: 

```erb
<% @items.each do |item| %>
  <div>Something with <%= item.title %></div>
  <%= render(SomeComponentReflex.new(item: item)) %>
<% end %>
```
But due to the way the key is computed https://github.com/joshleblanc/view_component_reflex/blob/d13da61d0a6d150840de19ee651588b1a1b205f0/lib/view_component_reflex/component.rb#L189
every component in this loop will have the same key.
I've seen that we can overcome this issue by using `collection_key` but it feels a hack somehow.

For instance the key could also hash the params.

What do you think?

**Comment by joshleblanc** [comment]
`collection_key` is functionally equivalent to passing a `key` prop in react. You need some way to associate the component with the index in the array.

I've spent quite a bit of time trying to figure out how we could eliminate the `caller` call from that method, and I genuinely don't believe there's a way for any state adapter except DOM.

If you're using the dom adapter, I think it'll "just work", since we don't need to reconcile state from an external source.

@arambert
