### ISSUE TITLE
Default key generation algorithm is very brittle

### ISSUE THREAD

**Issue by suan** [joshleblanc/view_component_reflex#16]
Sorry don't mean to be hard, this is a great library and I want it to improve!

But on the issue, case in point: by default if I render the same component multiple times from a view (they might not even be in a collection, I might have them multiple times on a page used in different ways)... they get the same key, and of course all kinds of bad things happen!

I think at the very least this should be made loud and clear in the README, and ideally the issue is fixed such that each component instance gets its own unique key. Why not base it off of the component instance's Ruby `object_id` or something?

P/S: This would also solve the issue of not being able to render a view-component from outside of a view (say from the backend for cable-ready...)

**Comment by joshleblanc** [comment]
You can safely put multiple components on the same page. The key generation takes into account the line number.

If you're rendering multiple components in the same file & line, you can use `collection_key` to append an identifier unique to that component. It's mentioned here: https://github.com/joshleblanc/view_component_reflex#collections.

I know the key generation is trash, but I needed something that would generate the same key across multiple workers and requests. We can't use the object_id because we're instantiating new objects every time a reflex comes in, and they wouldn't be the same across workers anyway.

The best solution I've had in the back of my mind is just throwing the state right on the component root, in a data attribute or something. Then we can just parse that back when we receive the reflex.

**Comment by suan** [comment]
Ah, turns out I was running into this when rendering multiple instances the component in a loop (hence same line)

For now I've just put a 

```ruby
  def collection_key
    self.object_id
  end
```

in a shared `ApplicationComponent` so I never have to worry about it again
